version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: movieseat
    hostname: movieseat
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movieseat
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
  pgadmin-data:
